
POST http://localhost:5233/api/discussions/69fb5b729a1de85c58c3bb73/vote
Content-Type: application/json

{
  "optionText": "Agree",
  "userName": "ann"
}
### Vote by User 2 


POST http://localhost:5233/api/discussions/69fb5b729a1de85c58c3bb73/vote
Content-Type: application/json

{
  "optionText": "Disagree",
  "userName": "mali"
}


### Vote by User 3
POST http://localhost:5233/api/discussions/69fb5adb9a1de85c58c3bb70/vote
Content-Type: application/json

{
  "optionText": "Disagree",
  "userName": "bob"
}

***************************************

### Vote by User 4
POST http://localhost:5233/api/discussions/69fb58b59a1de85c58c3bb58/vote
Content-Type: application/json

{
  "optionText": "Disagree",
  "userName": "charlie"
}

### Vote by User 5
POST http://localhost:5233/api/discussions/69fb56f69a1de85c58c3bb56/vote
Content-Type: application/json

{
  "optionText": "Disagree",
  "userName": "harry"
}

### Vote by User 5
POST http://localhost:5233/api/discussions/69fb56f69a1de85c58c3bb56/vote
Content-Type: application/json

{
  "optionText": "Disagree",
  "userName": "hu"
}






***************

### Vote by User 3
POST http://localhost:5233/api/discussions/69fb56f69a1de85c58c3bb56/vote
Content-Type: application/json

{
  "optionText": "Agree",
  "userName": "sarah"
}


### Vote by User 3
POST http://localhost:5233/api/discussions/69fb56f69a1de85c58c3bb56/vote
Content-Type: application/json

{
  "optionText": "Agree",
  "userName": "sarah"
}

### vote box creation

POST http://localhost:5233/api/discussions
Content-Type: application/json

{
  "tripId": "69eec832d470b3504402b83b", 
  "title": "Visit Sigiriya Rock",
  "description": "Shall we go there on Saturday morning?",
  "type": "Trip",
  "memberLimit": 3,
  "createdBy": "Admin"
}

### message sending
POST http://localhost:5233/api/comments
Content-Type: application/json

{
  "tripId": "69eec832d470b3504402b83b", 
  "userName": "Kasun",
  "text": "Hello everyone! This is a test message.",
  "messageType": "text"
}

### message sending

POST http://localhost:5233/api/comments
Content-Type: application/json

{
  "tripId": "69eec832d470b3504402b83b", 
  "userName": "tester",
  "text": "Hello ",
  "messageType": "text"
}



### Vote by User 3
POST http://localhost:5233/api/discussions/69fb56569a1de85c58c3bb55/vote
Content-Type: application/json

{
  "optionText": "Agree",
  "userName": "ama"
}