
POST http://localhost:5233/api/discussions/69ecc2f3d2077f9da6a167c0/vote
Content-Type: application/json

{
  "optionText": "Agree",
  "userName": "ann"
}


### Vote by User 2 (Bob)
POST http://localhost:5233/api/discussions/69ecc2f3d2077f9da6a167c0/vote
Content-Type: application/json

{
  "optionText": "Disagree",
  "userName": "bob"
}

### Vote by User 2 (Charlie)
POST http://localhost:5233/api/discussions/69ecc2f3d2077f9da6a167c0/vote
Content-Type: application/json

{
  "optionText": "Disagree",
  "userName": "charlie"
}

### Vote by User 3
POST http://localhost:5233/api/discussions/69ecbda0d2077f9da6a167bd/vote
Content-Type: application/json

{
  "optionText": "Disagree",
  "userName": "harry"
}

### Vote by User 3
POST http://localhost:5233/api/discussions/69ecbda0d2077f9da6a167bd/vote
Content-Type: application/json

{
  "optionText": "Agree",
  "userName": "sarah"
}
